# config/validator/validation.yaml
App\Entity\Measurments:
  properties:
    temp_day:
      - NotBlank: ~
      - Range:
          min: -50
          max: 50
    temp_night:
      - NotBlank: ~
      - Range:
          min: -50
          max: 50
    humidity:
      - NotBlank: ~
      - Range:
          min: 0
          max: 100
    wind:
      - NotBlank: ~
      - Range:
          min: 0
          max: 100
    precipation:
      - NotBlank: ~
      - Range:
          min: 0
          max: 100
    date:
      - Date: ~